version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        versions: ["0.0.0"]
      - dependency-name: "typescript"
        versions: ["5.0.0"]
      - dependency-name: "@types/node"
        versions: ["20.0.0"] 