name: legal-marketplace-sa
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: YOUR_USERNAME/legal-marketplace-sa
  dockerfile_path: Dockerfile
  http_port: 5000
  instance_count: 1
  instance_size_slug: basic-xs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: MONGODB_URI
    value: ${MONGODB_URI}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: STRIPE_SECRET_KEY
    value: ${STRIPE_SECRET_KEY}
  - key: CLIENT_URL
    value: ${CLIENT_URL} 